name: Publish Package

on:
  push:
    branches:
      - configure-releases-publish-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - name: Bump version and push tag
        id: tag_version
        run: |
          if [[ "$(git log -1 --pretty=%B)" == *"[BREAK]"* ]]; then 
            npm version major --no-git-tag-version
          elif [[ "$(git log -1 --pretty=%B)" == *"[FEATURE]"* ]]; then 
            npm version minor --no-git-tag-version
          else
            npm version patch --no-git-tag-version
          fi
          echo ::set-output name=VERSION::$(node -p "require('./package.json').version")
          git config --global user.email "hello@manneta.com"
          git config --global user.name "Akahige"
          git commit -am "Bump version"
          git tag "v$(node -p -e "require('./package.json').version")"
          git push --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
